keypair: robertskey
security_group: ssh-access
instance_type: t2.micro
ami: ami-29ebb519
vpc_subnet_id: subnet-8f72f1ea
region: us-west-2a
instance_tags: {"Name": "ansible-built"}
root_ebs_size: 8
zone: us-west-2a
instance_profile_name: imager
num_instances: 1
